package=org.encalmo.example
packaged=$package;format="packaged"$
repository=encalmo/example
organization=org.encalmo
name=example
nameCamel=$name;format="Camel"$
nameHyphen=$name;format="normalize"$
name=$nameHyphen$