package=org.encalmo.example
packaged=$package;format="packaged"$
scm=encalmo/example
scmHyphen=$scm;format="normalize"$
organization=org.encalmo
name=example
nameCamel=$name;format="Camel"$
name=$scmHyphen$